services:
  app:
    build: .
    ports:
      - "5000"
    environment:
      # Cesta k databazi v perzistentnim ulozisti /data
      - DATABASE_URL=sqlite:////data/database.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
